# array creations        1 np.array

In [2]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


# np.zeros()

In [5]:
a=np.zeros((2,3))
print(a)# in this give the range


[[0. 0. 0.]
 [0. 0. 0.]]


# np.ones()

In [7]:
b=np.ones((4,4)) # in this also we give the range
print(b)     # all value are in fllat value bydifualt

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# np.full()

In [8]:
c=np.full((2,3),10) # in this array full with the specific value like(10) 
print(c)

[[10 10 10]
 [10 10 10]]


# np.empty()

In [10]:
# np.empty()   in this array without initialize value fast but it give the random values
d=np.empty((2,3))
print(d)

[[6.23042070e-307 4.67296852e-307 1.69121096e-306]
 [1.24611266e-306 3.72364481e-317 1.39067116e-308]]


# np.arange()

In [12]:
n= np.arange(0,10,4) #in this arange function we give thre 3 parameter first is start 
print(n)          #and second is stop aand third is the steps """

[0 4 8]


# np.linespace()

In [16]:
# create a evenly spaced value in between two numbers
c=np.linspace(1,2,5)
print(c)

[1.   1.25 1.5  1.75 2.  ]


# np.eye()

In [17]:
# its create a identity matrix
c=np.eye(4)  # in eye() is take only 1 paremeter
print(c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# np.identity()

In [18]:
# its the similer to np.eye() it create the identyty matrix
b=np.identity(4) # in this take only 1 paremter
print(b)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# np.diag()

In [19]:
# its create the diagonal matrix and extract the diagonal value
v=np.diag([1,2,3]) 
print(v)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


# array inspection functions

# .ndim means ndiamentions

In [26]:
# it gives the numbners of the diamentions (axes ) of the array
import numpy as np     # its find the what kind of the matrix like (1d, 2d, 3d, nd)
a=np.array([[1,2,3],[4,5,6]])
print(a.ndim)

2


# .shape

In [29]:
# return the size of the array along the each diamention
print(a.shape) # shape is 1(find the row and column)

(2, 3)


# .size

In [31]:
# total number of the element in the array
print(a.size)  # it gives the total elemetn

6


# .dtype

In [34]:
print(a.dtype) # its give the data type of the arrray

int64


# .itemsize

In [39]:
#size of each element
#int8	1 byte
#int16	2 bytes
#int32	4 bytes
#int64	8 bytes
#float32	4 bytes
#float64	8 bytes
#bool	1 byte
# byte per element  means how much memory cunsupetion to save element
print(a.itemsize)
print(a.dtype)

8
int64


# .isscalar

In [43]:
# check if the input is single numbner or not
print(np.isscalar(5)) # it means we are pass 1 value than true eithor false
print(np.isscalar([1,2]))

True
False


# .iscomplex

In [55]:
# is check the elements are compelex numer
c=np.array([1,32,5,44,2+4j,np.inf,np.nan])
print(np.iscomplex(c)) # is chech the complex numer when is exxit than give true

[False False False False  True False False]


# .isreal()

In [56]:
# chech if element are real numers
print(np.isreal(c))

[ True  True  True  True False  True  True]


# .isfinite()

In [57]:
# check if  the elements are finite or not
print(np.isfinite(c))

[ True  True  True  True  True False False]


# .isnan()

In [58]:
# check if element is NaN(not a number)
print(np.isnan(c))

[False False False False False False  True]


# array manupilation and functions

# (1).reshape()

In [62]:
# changing the shape of the array withut changing the data
import numpy as np
a=np.arange(6)
print(a)

b=a.reshape((2,3))
print(b)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


# (2).ravel()

In [64]:
# flat the array into 1d array abd return= aview when a possible
print(b.ravel())

[0 1 2 3 4 5]


# (3).flatten()

In [65]:
# is similer to ravel() but alwayes gives the return a copy
print(b.flatten())

[0 1 2 3 4 5]


# (4).transpose()

In [66]:
#Swaps rows and columns (generalized for higher dimensions).
print(b.transpose())


[[0 3]
 [1 4]
 [2 5]]


# (5).swapaxes()

In [73]:
# swap two axex in array 
c = np.arange(8).reshape(2,2,2)
print(c.swapaxes(0, 2))

[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


# (6).moveaxis()

In [74]:
#Moves an axis to a new position.
d = np.ones((2, 3, 4))
print(np.moveaxis(d, 0, -1).shape)  # (3, 4, 2)

(3, 4, 2)


# (7).concatenate()

In [77]:
#Joins arrays along an existing axis
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
print(np.concatenate((x, y), axis=0))


[[1 2]
 [3 4]
 [5 6]]


# (8).stack()

In [78]:
# Joins arrays along a new axis.
a = np.array([1, 2])
b = np.array([3, 4])
print(np.stack((a, b)))


[[1 2]
 [3 4]]


# (9).hstack() and .vstack()

In [79]:
#Horizontal and vertical stacking.
print(np.hstack((a, b)))  
print(np.vstack((a, b)))


[1 2 3 4]
[[1 2]
 [3 4]]


# (10).split()

In [81]:
#  splits an array into multiple sub-arrays.
arr = np.arange(9)
print(np.split(arr, 3))


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


# mathemetical operations  in numpy

#  addition and multiplication

In [82]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

print(a+b)
print(a*b)

[ 6  8 10 12]
[ 5 12 21 32]


In [84]:
a=np.array([10,20,30])
b=np.array([1,2,3])
print(a-b)
print(a/b)

[ 9 18 27]
[10. 10. 10.]


# exponential and logarithams

In [85]:
#NumPy has built-in functions for exponential growth and logarithms.
x=np.array([1,2,3])
print(np.exp(x))
print(np.log(x))

[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]


In [86]:
print(np.log(0))

-inf


C:\Users\niles\AppData\Local\Temp\ipykernel_16156\2955966184.py:1: RuntimeWarning: divide by zero encountered in log
  print(np.log(0))


# trigonometry